routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', array( 'as' => 'admin.home', 'uses' => 'HomeController@index' ));

    // Artist
    Route::model('artist', 'App\Models\Artist');
    Route::get( '/artist/{artist}/delete', array( 'as' => 'artist.delete', 'uses' => 'ArtistController@delete' ) );
    Route::resource('artist', 'ArtistController');

    // ArtistMeta
    Route::model('artist-meta', 'App\Models\ArtistMeta');
    Route::resource('artist-setting', 'ArtistMetaController');

    // Personnel
    Route::model('personnel', 'App\Models\Personnel');
    Route::get( '/personnel/{personnel}/delete', array( 'as' => 'personnel.delete', 'uses' => 'PersonnelController@delete' ) );
    Route::post( '/personnel/save-order', array( 'as' => 'personnel.save-order', 'before' => 'csrf', 'uses' => 'PersonnelController@save_order' ) );
    Route::resource('personnel', 'PersonnelController');

    // Album
    Route::model('album', 'App\Models\Album');
    Route::get( '/album/{album}/delete', array( 'as' => 'album.delete', 'uses' => 'AlbumController@delete' ) );
    Route::resource('album', 'AlbumController');

    // AlbumMeta
    Route::model('album-meta', 'App\Models\AlbumMeta');
    Route::resource('album-setting', 'AlbumMetaController');

    // AlbumMusicbrainz
    Route::post( '/album-musicbrainz/search', array( 'as' => 'album-musicbrainz.search', 'uses' => 'AlbumMusicbrainzController@index' ) );
    Route::resource( 'album-musicbrainz', 'AlbumMusicbrainzController' );

    // AlbumDiscogs
    Route::post( '/album-discogs/search', array( 'as' => 'album-discogs.search', 'uses' => 'AlbumDiscogsController@index' ) );
    Route::resource( 'album-discogs', 'AlbumDiscogsController' );

    // Release
    Route::model('release', 'App\Models\Release');
    Route::get( '/release/{release}/delete', array( 'as' => 'release.delete', 'uses' => 'ReleaseController@delete' ) );
    Route::resource('release', 'ReleaseController');

    // ReleaseMeta
    Route::model('release-meta', 'App\Models\ReleaseMeta');
    Route::resource('release-setting', 'ReleaseMetaController');

    // Tracks
    Route::model('track', 'App\Models\Track');
    Route::get( '/track/{track}/delete', array( 'as' => 'track.delete', 'uses' => 'TrackController@delete' ) );
    Route::post( '/track/save-order', array( 'as' => 'track.save-order', 'before' => 'csrf', 'uses' => 'TrackController@save_order' ) );
    Route::resource('track', 'TrackController');

    // TrackMeta
    Route::model('track-meta', 'App\Models\TrackMeta');
    Route::resource('track-setting', 'TrackMetaController');
});



// Authentication
Auth::routes();

//Route::get( '/login', array( 'as' => 'auth.login', 'uses' => 'AuthController@login') );
//Route::get( '/logout', array( 'as' => 'auth.logout', 'uses' => 'AuthController@sign_out' ) );
//Route::post( '/signin', array( 'as' => 'auth.signin', 'uses' => 'AuthController@sign_in' ) );

resources/views/index.blade.php
@extends('layout')

@section('page_title')
 &raquo; Administration
@stop

@section('section_header')
<h2>Home</h2>
@stop

@section('section_label')

@stop

@section('seciton_sublabel')
@stop

@section('content')

<div class="col-md-12">
	<ul>
		<li><a href="{{ route( 'artist.index', array('browse' => 'a') ) }}">Manage artists</a></li>
	</ul>
</div>

@stop

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en-us">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>
		Musicwhore.org Administration
		@yield('page_title')
	</title>
	<meta http-equiv="Content-type" content="text/html; charset=UTF-8" />
	<meta name="viewport" content="width=device-width">
	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
	<link rel="stylesheet" href="{{ VIGILANTMEDIA_CDN_BASE_URI }}/web/css/chosen.min.css" type="text/css" />
	<link rel="stylesheet" href="/css/typography.css" type="text/css" media="all" />
	<link rel="stylesheet" href="/css/layout.css" type="text/css" media="screen, projection" />
	<link rel="stylesheet" href="//code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" type="text/css" />
	<link href='//fonts.googleapis.com/css?family=Merriweather&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
	<link href='//fonts.googleapis.com/css?family=Merriweather+Sans&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
	<link href='//fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
	<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
	<script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
	<script type="text/javascript" src="//code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="{{ VIGILANTMEDIA_CDN_BASE_URI }}/web/js/chosen.jquery.min.js"></script>
</head>
<body>
	<div class="container">
		<header class="row">
			<div class="hidden-xs col-md-12">
				<h1 class="site-title">
					Musicwhore.org
					<small>Administration</small>
				</h1>
			</div>

			<nav class="navbar navbar-inverse col-md-12" role="navigation">
				<div class="container-fluid">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-nav">
							<a class="sr-only" href="#content">Skip to content</a>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<div class="visible-xs">
							<a href="{{ route( 'admin.home' ) }}" class="navbar-brand">Musicwhore.org Administration</a>
						</div>
					</div>
					<div id="bs-nav" class="collapse navbar-collapse">
						<ul class="nav navbar-nav">
							<li><a href="{{ route('admin.home') }}">Home</a></li>
                            @guest
                                <li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                            @else
                                <li>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </li>
                            @endguest
						</ul>
					</div>
				</div>
			</nav>
		</header>

		<div class="row">
			<div class="col-md-12">
				@yield('section_header')

				@yield('section_label')

				@yield('section_sublabel')

				@if ( Session::get('message') != '')
				<div class="alert alert-success alert-dismissable">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					{{ Session::get('message') }}
				</div>
				@endif

				@if ( Session::get('error') != '')
				<div class="alert alert-danger alert-dismissable">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					{{ Session::get('error') }}
				</div>
				@endif

				<div class="row">
					@yield('content')

					@yield('sidebar')
				</div>
			</div>
		</div>
	</div>
</body>
</html>