routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', array( 'as' => 'admin.home', 'uses' => 'HomeController@index' ));

    // Artist
    Route::model('artist', 'App\Models\Artist');
    Route::get( '/artist/{artist}/delete', array( 'as' => 'artist.delete', 'uses' => 'ArtistController@delete' ) );
    Route::resource('artist', 'ArtistController');

    // ArtistMeta
    Route::model('artist-meta', 'App\Models\ArtistMeta');
    Route::resource('artist-setting', 'ArtistMetaController');

    // Personnel
    Route::model('personnel', 'App\Models\Personnel');
    Route::get( '/personnel/{personnel}/delete', array( 'as' => 'personnel.delete', 'uses' => 'PersonnelController@delete' ) );
    Route::post( '/personnel/save-order', array( 'as' => 'personnel.save-order', 'before' => 'csrf', 'uses' => 'PersonnelController@save_order' ) );
    Route::resource('personnel', 'PersonnelController');

    // Album
    Route::model('album', 'App\Models\Album');
    Route::get( '/album/{album}/delete', array( 'as' => 'album.delete', 'uses' => 'AlbumController@delete' ) );
    Route::resource('album', 'AlbumController');

    // AlbumMeta
    Route::model('album-meta', 'App\Models\AlbumMeta');
    Route::resource('album-setting', 'AlbumMetaController');

    // AlbumMusicbrainz
    Route::post( '/album-musicbrainz/search', array( 'as' => 'album-musicbrainz.search', 'uses' => 'AlbumMusicbrainzController@index' ) );
    Route::resource( 'album-musicbrainz', 'AlbumMusicbrainzController' );

    // AlbumDiscogs
    Route::post( '/album-discogs/search', array( 'as' => 'album-discogs.search', 'uses' => 'AlbumDiscogsController@index' ) );
    Route::resource( 'album-discogs', 'AlbumDiscogsController' );

    // Release
    Route::model('release', 'App\Models\Release');
    Route::get( '/release/{release}/delete', array( 'as' => 'release.delete', 'uses' => 'ReleaseController@delete' ) );
    Route::resource('release', 'ReleaseController');

    // ReleaseMeta
    Route::model('release-meta', 'App\Models\ReleaseMeta');
    Route::resource('release-setting', 'ReleaseMetaController');

    // Tracks
    Route::model('track', 'App\Models\Track');
    Route::get( '/track/{track}/delete', array( 'as' => 'track.delete', 'uses' => 'TrackController@delete' ) );
    Route::post( '/track/save-order', array( 'as' => 'track.save-order', 'before' => 'csrf', 'uses' => 'TrackController@save_order' ) );
    Route::resource('track', 'TrackController');

    // TrackMeta
    Route::model('track-meta', 'App\Models\TrackMeta');
    Route::resource('track-setting', 'TrackMetaController');
});



// Authentication
Auth::routes();

//Route::get( '/login', array( 'as' => 'auth.login', 'uses' => 'AuthController@login') );
//Route::get( '/logout', array( 'as' => 'auth.logout', 'uses' => 'AuthController@sign_out' ) );
//Route::post( '/signin', array( 'as' => 'auth.signin', 'uses' => 'AuthController@sign_in' ) );

app/Models/Album.php
<?php
/**
 * Created by PhpStorm.
 * User: gregbueno
 * Date: 5/26/14
 * Time: 5:26 PM
 */
namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Album extends Model {

	protected $table = 'mw_albums';
	protected $primaryKey = 'album_id';
	protected $softDelete = true;
	protected $fillable = array(
		'album_artist_id',
		'album_format_id',
		'album_title',
		'album_sort_title',
		'album_alt_title',
		'album_label',
		'album_release_date',
		'album_image',
	);
	protected $guarded = array(
		'album_id',
	);

	public function artist() {
		return $this->belongsTo('App\Models\Artist', 'album_artist_id', 'artist_id');
	}

	public function releases() {
		return $this->hasMany('App\Models\Release', 'release_album_id', 'album_id');
	}

	public function meta() {
		return $this->hasMany('App\Models\AlbumMeta', 'meta_album_id', 'album_id');
	}

	public function format() {
		return $this->hasOne('App\Models\AlbumFormat', 'format_id', 'album_format_id');
	}
}

app/Http/Controllers/AlbumController.php
<?php

namespace App\Http\Controllers;

use App\Models\Album;
use App\Models\AlbumFormat;
use App\Models\Artist;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Request;
use Illuminate\Support\Facades\View;
use \Guzzle\Http\Client;
use \MusicBrainz\Filters\ReleaseGroupFilter;
use \MusicBrainz\HttpAdapters\GuzzleHttpAdapter;
use \MusicBrainz\MusicBrainz;
use \Discogs;

class AlbumController extends Controller {

	private $layout_variables = array();

	public function __construct() {
		global $config_url_base;

		$format_list = array();
		$formats = AlbumFormat::orderBy('format_alias')->get();
		foreach ($formats as $format) {
			$format_list[$format->format_id] = $format->format_alias;
		}

		$this->layout_variables = array(
			'config_url_base' => $config_url_base,
			'formats' => $format_list,
			'locales' => array('en', 'jp'),
		);
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Contracts\View\View
	 */
	public function index()
	{
		$artist_id = Request::get('artist');
		if (!empty($artist_id)) {
			$albums = Album::where('album_artist_id', $artist_id)->orderBy('album_title')->get();
		} else {
			$albums = Album::orderBy('album_title')->get();
		}
		$albums->load('artist');

		$method_variables = array(
			'albums' => $albums,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('album.index', $data);
	}


	/**
	 * Show the form for creating a new resource.
	 *
     * @return \Illuminate\Contracts\View\View
	 */
	public function create()
	{
		$artist_id = Request::get('artist');

		$album = new Album;
		$album->album_release_date = date('Y-m-d');
		$album->album_ctype_locale = 'en';
		if (!empty($artist_id)) {
			$album->album_artist_id = $artist_id;
			$album->artist = Artist::find($artist_id);
		}

		$artists = Artist::with('meta')->select(array('artist_id', 'artist_last_name', 'artist_first_name', 'artist_display_name'))->orderBy('artist_last_name')->get()->pluck('artist_display_name', 'artist_id');

		$method_variables = array(
			'album' => $album,
			'artists' => $artists,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('album.create', $data);
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return RedirectResponse
	 */
	public function store()
	{
		$id = new Album;

		$fields = $id->getFillable();

		foreach ($fields as $field) {
			$id->{$field} = Request::get($field);
		}

		$result = $id->save();

		if ($result !== false) {
			return Redirect::route('album.show', array('album' => $id->album_id))->with('message', 'Your changes were saved.');
		} else {
			return Redirect::route('artist.show', array('artist' => $id->album_artist_id))->with('error', 'Your changes were not saved.');
		}
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
     * @return \Illuminate\Contracts\View\View
	 */
	public function show($id)
	{
		$method_variables = array(
			'album' => $id,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('album.show', $data);
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
     * @return \Illuminate\Contracts\View\View
	 */
	public function edit($id)
	{
		$releases = $id->releases->pluck('release_catalog_num', 'release_id');
		$artists = Artist::with('meta')->select(array('artist_id', 'artist_last_name', 'artist_first_name', 'artist_display_name'))->orderBy('artist_last_name')->get()->pluck('artist_display_name', 'artist_id');

		$method_variables = array(
			'album' => $id,
			'releases' => $releases,
			'artists' => $artists,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('album.edit', $data);
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  Album  $id
	 * @return RedirectResponse
	 */
	public function update($id)
	{
		$fields = $id->getFillable();

		foreach ($fields as $field) {
			$id->{$field} = Request::get($field);
		}

		$result = $id->save();

		if ($result !== false) {
			return Redirect::route('album.show', array('album' => $id->album_id))->with('message', 'Your changes were saved.');
		} else {
			return Redirect::route('artist.show', array('album' => $id->album_artist_id))->with('error', 'Your changes were not saved.');
		}
	}


	/**
	 * Show the form for deleting the specified resource.
	 *
	 * @param  int  $id
     * @return \Illuminate\Contracts\View\View
	 */
	public function delete($id) {

		$method_variables = array(
			'album' => $id,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('album.delete', $data);
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return RedirectResponse
	 */
	public function destroy($id)
	{
		$confirm = (boolean) Request::get('confirm');
		$album_title = $id->album_title;
		$artist_id = $id->album_artist_id;

		if ($confirm === true) {
			if (count($id->releases) > 0) {
				foreach ($id->releases as $release) {
					/*
					 * This bit of logic is not yet supported.
					foreach ($release->tracks as $track) {
						$track->ecommerce()->delete();
					}
					 */

					// Remove ecommerce.
					$release->ecommerce()->delete();

					// Remove tracks.
					$release->tracks()->delete();
				}

				// Remove releases.
				$id->releases()->delete();
			}

			// Remove album.
			$id->delete();
			return Redirect::route('artist.show', array('artist' => $artist_id  ))->with('message', $album_title . ' was deleted.');
		} else {
			return Redirect::route('album.show', array('album' => $id->album_id))->with('error', $album_title . ' was not deleted.');
		}
	}


	/**
	 * Save the order of albums.
	 *
	 * @return void
	 */
	public function save_order() {
		$albums = Request::get('albums');

		$is_success = true;
		if (count($albums) > 0) {
			foreach ($albums as $album) {
				if (false === $this->_update_album($album['album_id'], $album)) {
					$is_success = false;
					$error = 'Album order was not saved.';
					break;
				}
			}
		}

		echo ($is_success == true) ? 'Album order has been saved.' : $error;
	}

	private function _update_album($album_id, $input) {
		$album = Album::find($album_id);

		$album->album_order = $input['album_order'];

		return $album->save();
	}

	public function lookup_discogs($id) {

		$discogs = new Discogs\Service();

		$args = array(
			'q' => $id->album_title,
			'artist' => $id->artist->artist_display_name,
			'type' => 'master',
		);

		$master_releases = $discogs->search( $args );

		$method_variables = array(
			'album' => $id,
			'artist' => $id->artist->artist_display_name,
			'q_master_release' => $id->album_title,
			'master_releases' => $master_releases,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('album.discogs.lookup', $data);
	}

	public function search_discogs() {

		$discogs = new Discogs\Service();

		$q_master_release = Request::get('q_master_release');
		$artist = Request::get('artist');
		$id = Request::get('id');

		$args = array(
			'q' => $q_master_release,
			'artist' => $artist,
			'type' => 'master',
		);

		$master_releases = $discogs->search( $args );

		$method_variables = array(
			'album' => Album::find($id),
			'artist' => $artist,
			'q_master_release' => $q_master_release,
			'master_releases' => $master_releases,
		);

		$data = array_merge($method_variables, $this->layout_variables);

		return View::make('album.discogs.lookup', $data);
	}
}

resources/views/album/musicbrainz/_form.blade.php
@extends('album._form')

@section('content')
@parent

<h4>Settings</h4>

<div class="form-group">
	{{ Form::label( 'musicbrainz_gid', 'Musicbrainz GID:', array( 'class' => 'control-label col-md-2' ) ) }}
	<div class="col-md-10">
		{{ Form::text( 'musicbrainz_gid', $gid, array( 'class' => 'form-control' ) ) }}
	</div>
</div>

<div class="form-group">
	<div class="col-md-offset-2 col-md-10">
		{{ Form::submit( 'Save', array( 'class' => 'btn btn-default' ) ) }}
	</div>
</div>

@stop

resources/views/album/musicbrainz/create.blade.php
@extends('album.musicbrainz._form')

@section('page_title')
 &raquo; {{ $album->artist->artist_display_name }}
 &raquo; Albums &raquo; Musicbrainz Import
@stop

@section('section_header')
<h2>{{ $album->artist->artist_display_name }}</h2>
@stop

@section('section_label')
<h3>Musicbrainz import</h3>
@stop

@section('content')
{{ Form::model( $album, array( 'route' => 'album-musicbrainz.store', 'class' => 'form-horizontal', 'role' => 'form' ) ) }}
@parent
{{ Form::close() }}
@stop

resources/views/album/musicbrainz/edit.blade.php
@extends('album.musicbrainz._form')

@section('page_title')
 &raquo; {{ $album->artist->artist_display_name }}
 &raquo; {{ $album->album_title }}
 &raquo; Musicbrainz Import
@stop

@section('section_header')
<h2>
	{{ $album->artist->artist_display_name }}
	<small>{{ $album->album_title }}</small>
</h2>
@stop

@section('section_label')
<h3>Musicbrainz import</h3>
@stop

@section('content')
{{ Form::model( $album, array( 'route' => array('album-musicbrainz.update', $album->album_id), 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'put' ) ) }}
@parent
{{ Form::close() }}
@stop

resources/views/album/musicbrainz/index.blade.php
@extends('layout')

@section('page_title')
 &raquo; {{ $artist->artist_display_name }}
@if (!empty($album->album_title))
 &raquo; {{ $artist->album_title }}
@endif
 $raquo; Musicbrainz
@stop

@section('section_header')
<h2>
	{{ $artist->artist_display_name }}
	@if (!empty($album->album_title))
	<small>{{ $artist->album_title }}</small>
	@endif
</h2>
@stop

@section('section_label')
<h3>Musicbrainz</h3>
@stop

@section('content')

@if (!empty($album->album_id))
{{ Form::open( array( 'route' => array('album-setting.update', $album->album_id), 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'put' ) ) }}

{{ Form::submit( 'Save', array( 'class' => 'btn btn-default' ) ) }}
@else
{{ Form::open( array( 'route' => 'album-musicbrainz.create', 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'get' ) ) }}

{{ Form::submit( 'Import', array( 'class' => 'btn btn-default' ) ) }}
@endif

{{ Form::hidden( 'album_artist_id', $artist->artist_id ) }}

@foreach ($brainz_artist->{'release-groups'} as $release_group)
<div class="form-group">
	<div class="col-sm-12">
		<div class="radio">
			<label class="mb-result" title="{{ $release_group['id'] }}" data-toggle="tooptip" data-placement="above">
				{{ Form::radio( 'musicbrainz_gid', $release_group['id'] ) }}
				<a href="http://musicbrainz.org/release-group/{{ $release_group['id'] }}">{{ $release_group['title'] }}</a>
			</label>
		</div>
	</div>
</div>
@endforeach

{{ Form::submit( (!empty( $album->album_id )) ? 'Save' : 'Import', array( 'class' => 'btn btn-default' ) ) }}

{{ Form::close() }}
<script type="text/javascript">
	(function ($) {
		$(function () {
			$('.mb-result').tooltip();
		});
	})(jQuery);
</script>
@stop

resources/views/album/musicbrainz/lookup.blade.php
@extends('layout')

@section('page_title')
@if (!empty($album))
 &raquo; {{ $album->artist->artist_display_name }}
 &raquo; {{ $album->album_title }}
@endif
 &raquo; Musicbrainz lookup
@stop

@section('section_header')
<hgroup>
	<h2>
		@if (!empty($album))
		{{ $album->artist->artist_display_name }}
		<small>{{ $album->album_title }}</small>
		@endif
	</h2>
</hgroup>
@stop

@section('section_label')
<h3>Musicbrainz lookup</h3>
@stop

@section('content')
<div class="col-md-12">
	{{ Form::open( array( 'route' => 'album-setting.musicbrainz.search', 'class' => 'form-horizontal' ) ) }}
	<div class="form-group">
		<div class="col-md-10">
			{{ Form::text( 'q_release_group', $q_release_group, array( 'class' => 'form-control' ) ) }}
		</div>
		<div class="col-md-2">
			{{ Form::submit( 'Search', array( 'class' => 'btn btn-default' ) ) }}
			{{ Form::hidden( 'arid', $album->artist->meta->musicbrainz_gid ) }}
			{{ Form::hidden( 'artist', $album->artist->artist_display_name ) }}
			{{ Form::hidden( 'id', $album->album_id ) }}
		</div>
	</div>
	{{ Form::close() }}

	@if (count($release_groups) > 0)
	{{ Form::model( $album, array( 'route' => array('album-setting.update', $album->album_id), 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'put' ) ) }}

	{{ Form::submit( 'Save', array( 'class' => 'btn btn-default' ) ) }}

	@foreach ($release_groups as $release_group)
	<div class="form-group">
		<div class="col-sm-12">
			<div class="radio">
				<label class="mb-result" title="{{ $release_group->id }}" data-toggle="tooptip" data-placement="above">
					{{ Form::radio( 'musicbrainz_gid', $release_group->getId(), ($album->meta->musicbrainz_gid != null && ($album->meta->musicbrainz_gid == $release_group->getId() ) ) ) }}
					<a href="http://musicbrainz.org/release-group/{{ $release_group->getId() }}">{{ $release_group->getTitle() }}</a>
				</label>
			</div>
		</div>
	</div>
	@endforeach

	{{ Form::submit( 'Save', array( 'class' => 'btn btn-default' ) ) }}

	{{ Form::close() }}
	<script type="text/javascript">
		(function ($) {
			$(function () {
				$('.mb-result').tooltip();
			});
		})(jQuery);
	</script>

	@else
	<p>
		No release groups were found for this album.
	</p>
	@endif


</div>
@stop

resources/views/album/musicbrainz/show.blade.php
@extends('layout')

@section('page_title')
 &raquo; {{ $album->artist->artist_display_name }}
@stop

@section('section_header')
<h2>{{ $album->artist->artist_display_name }}</h2>
@stop

@section('section_label')
<h3>Musicbrainz</h3>
@stop

@section('content')
<ul class="list-inline">
	<li><a href="{{ route( 'album-musicbrainz.edit', array( 'album_musicbrainz' => $gid, 'album' => $album->album_id ) )  }}" class="btn btn-default"><span class="glyphicon glyphicon-import"></span> Update</a></li>
</ul>

<ul class="list-unstyled">
	<li class="row">
		<label class="col-md-3">Title:</label>
		<div class="col-md-9">
			{{ $brainz_album->title }}
		</div>
	</li>
	<li class="row">
		<label class="col-md-3">Release date:</label>
		<div class="col-md-9">
			{{ $brainz_album->{'first-release-date'} }}
		</div>
	</li>
</ul>
@stop